# Build settings
theme: type-on-strap
# remote_theme: sylhare/Type-on-Strap

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-twitch
  - jekyll-youtube

# Site Settings
author:
  name: Princess Pluto
  picture: /img/setup.jpg
  twitter: pwnprincesspluto
baseurl: "" # the subpath of your site, e.g. /blog
description: >- # this means to ignore newlines until "baseurl:"
  Princess Pluto invites you into her domain of code, games, and more!
favicon: assets/favicon.png
future: true
tagline: A vTuber who codes and games.
title: Princess Pluto
twitter:
  username: ChaelCodes
  card: summary
social:
  name: ChaelCodes
  links:
    - https://twitch.tv/PwnPrincessPluto
    - https://twitter.com/PwnPrincessPluto
    - https://github.com/PwnPrincessPluto
url: "https://princesspluto.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  PwnPrincessPluto
twitter_username: PwnPrincessPluto

# Header and Footer
header_text: PwnPrincessPluto
header_feature_image: /assets/img/bagelbanner.jpg
footer_text: Cuddle your else's, Track your Performance, and Docker isn't Magic. <3

# Blog
excerpt: truncate

# PAGINATION
paginate: 10
paginate_path: "blog/page:num"

# Atom/RSS Feed
feed:

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
